version: "3"

services:
  backend:
    # build: ./backend
    image: workshop-docker-k8s-helm_backend
    ports:
      - 3000:3000

  frontend: 
    # build: ./frontend
    image: workshop-docker-k8s-helm_frontend
    ports:
      - 9999:80

  mongo:
    # build: ./database
    image: my_mongo:1.0
    # container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: mongo-test    
    # volumes:
    #   - ./data:/data/db
    #   - ./configdb:/data/configdb


  
